{
 "title": "API Status",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Requests counter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(litestar_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(litestar_requests_total[30s])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Request distribution",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(path, method) (litestar_requests_total{path!=\"/metrics\"})",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "rate(litestar_responses_total[30s])",
     "legendFormat": "{{method}} {{path}} {{status_code}}"
    }
   ]
  }
 ]
}