{
 "title": "Campaign Stats",
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "1970-01-01T00:00:00.005Z" },
 "templating": {
  "list": [
   {
    "name": "cmp_id",
    "label": "Campaign ID",
    "query": "SELECT campaign_id FROM metrics;"
   }
  ]
 },
 "panels": [
  {
   "title": "Conversion",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    COALESCE(\r\n            100.0 * SUM(\r\n                    CASE WHEN fact = 'CLICK' THEN 1 ELSE 0 END\r\n            ) / NULLIF(\r\n                    1.0 * SUM(CASE WHEN fact = 'SHOW' THEN 1 ELSE 0 END), 0\r\n            ),\r\n            0\r\n) as conv\r\nFROM metrics\r\nWHERE campaign_id = '$cmp_id'"
    }
   ]
  },
  {
   "title": "Views & Clicks",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fact, COUNT(fact) as cnt\r\nFROM metrics\r\nWHERE campaign_id = '$cmp_id'\r\nGROUP BY fact"
    }
   ]
  },
  {
   "title": "Total expense",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(cost) FROM metrics WHERE campaign_id = '$cmp_id' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Daily Conversion",
   "type": "trend",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT all_dates.date,\r\n    COALESCE(\r\n        100.0 * SUM(\r\n                CASE WHEN fact = 'CLICK' THEN 1 ELSE 0 END\r\n        ) / NULLIF(\r\n                1.0 * SUM(CASE WHEN fact = 'SHOW' THEN 1 ELSE 0 END), 0\r\n        ),\r\n        0\r\n    ) as conv FROM (WITH max_date AS (\r\n        SELECT max(metrics.date) as md from metrics\r\n    )\r\n    SELECT generate_series as date\r\n    FROM generate_series(0, (SELECT * FROM max_date))\r\n) as all_dates\r\nFULL OUTER JOIN (\r\n    SELECT date, fact, campaign_id\r\n    FROM metrics\r\n    WHERE campaign_id = '$cmp_id'\r\n) as f_metrics ON f_metrics.date = all_dates.date\r\nGROUP BY all_dates.date\r\nORDER BY all_dates.date ASC\r\nLIMIT 50"
    }
   ]
  },
  {
   "title": "Daily Views",
   "type": "trend",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT all_dates.date, COUNT(fact) FROM (WITH max_date AS (\r\n        SELECT max(metrics.date) as md from metrics\r\n    )\r\n    SELECT generate_series as date\r\n    FROM generate_series(0, (SELECT * FROM max_date))\r\n) as all_dates\r\nFULL OUTER JOIN (\r\n    SELECT date, fact, campaign_id\r\n    FROM metrics\r\n    WHERE (campaign_id = '$cmp_id' AND fact = 'SHOW')\r\n) as f_metrics ON f_metrics.date = all_dates.date\r\nGROUP BY all_dates.date\r\nORDER BY all_dates.date ASC\r\nLIMIT 50"
    }
   ]
  },
  {
   "title": "Daily Clicks",
   "type": "trend",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT all_dates.date, COUNT(fact) FROM (WITH max_date AS (\r\n        SELECT max(metrics.date) as md from metrics\r\n    )\r\n    SELECT generate_series as date\r\n    FROM generate_series(0, (SELECT * FROM max_date))\r\n) as all_dates\r\nFULL OUTER JOIN (\r\n    SELECT date, fact, campaign_id\r\n    FROM metrics\r\n    WHERE (campaign_id = '$cmp_id' AND fact = 'CLICK')\r\n) as f_metrics ON f_metrics.date = all_dates.date\r\nGROUP BY all_dates.date\r\nORDER BY all_dates.date ASC\r\nLIMIT 50"
    }
   ]
  },
  {
   "title": "Daily Expenses (combined)",
   "type": "trend",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT all_dates.date, COALESCE(SUM(cost), 0) as cost FROM (WITH max_date AS (\r\n        SELECT max(metrics.date) as md from metrics\r\n    )\r\n    SELECT generate_series as date\r\n    FROM generate_series(0, (SELECT * FROM max_date))\r\n) as all_dates\r\nFULL OUTER JOIN (\r\n    SELECT date, campaign_id, cost\r\n    FROM metrics\r\n    WHERE campaign_id = '$cmp_id'\r\n) as f_metrics ON f_metrics.date = all_dates.date\r\nGROUP BY all_dates.date\r\nORDER BY all_dates.date ASC\r\nLIMIT 50"
    }
   ]
  }
 ]
}