# Source: https://github.com/wemake-services/wemake-python-styleguide

line-length = 80

[lint]
ignore = [
    "A005",   # allow to shadow stdlib and builtin module names
    "COM812", # trailing comma, conflicts with `ruff format`
    # Different doc rules that we don't really care about:
    "D100",
    "D104",
    "D106",
    "D203",
    "D212",
    "D401",
    "D404",
    "D405",
    "ISC001",  # implicit string concat conflicts with `ruff format`
    "ISC003",  # prefer explicit string concat over implicit concat
    "PLR09",   # we have our own complexity rules
    "PLR2004", # do not report magic numbers
    "PLR6301", # do not require classmethod / staticmethod when self not used
    "TRY003",  # long exception messages from `tryceratops`

    # My own additions

    "N818",
    # Just wrong in every possible way. If class extends an Exception, then
    # it's an exception, not an Error. Moreover, Error is smth unrecoverable,
    # while Exception is not so scary and more routine.

    "S324",
    # This project does not need security in any way

    "RUF100",
    # does not detect wps
]
