"""add image to campaign

Revision ID: 702d28039ac2
Revises: b78a0983efe9
Create Date: 2025-02-15 14:54:01.685711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702d28039ac2'
down_revision: Union[str, None] = 'b78a0983efe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('image_uri', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'metrics', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metrics', type_='unique')
    op.drop_column('campaigns', 'image_uri')
    # ### end Alembic commands ###
