"""add indexes on metrics

Revision ID: 7c9738e67303
Revises: 690b6b4d1d0a
Create Date: 2025-02-21 02:16:55.737727

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7c9738e67303'
down_revision: Union[str, None] = '690b6b4d1d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('campaign_id_index', 'metrics', ['campaign_id'], unique=False, postgresql_using='hash')
    op.create_index('client_id_index', 'metrics', ['client_id'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('client_id_index', table_name='metrics', postgresql_using='hash')
    op.drop_index('campaign_id', table_name='metrics', postgresql_using='hash')
    # ### end Alembic commands ###
