"""Add metrics

Revision ID: b78a0983efe9
Revises: c440278e30b3
Create Date: 2025-02-13 16:58:59.455525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78a0983efe9'
down_revision: Union[str, None] = 'c440278e30b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('client_id', sa.UUID(), nullable=False),
        sa.Column('campaign_id', sa.UUID(), nullable=False),
        sa.Column('fact', sa.Enum('SHOW', 'CLICK', name='metrictype'), nullable=False),
        sa.Column('date', sa.Integer(), nullable=False),
        sa.Column('cost', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'campaigns', ['id'])
    op.create_unique_constraint(None, 'settings', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'settings', type_='unique')
    op.drop_constraint(None, 'campaigns', type_='unique')
    op.drop_table('metrics')
    # ### end Alembic commands ###
