"""add indexes on ml scores

Revision ID: b7f012ac8376
Revises: 7c9738e67303
Create Date: 2025-02-21 10:06:32.969475

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b7f012ac8376'
down_revision: Union[str, None] = '7c9738e67303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'metrics', ['id'])
    op.create_index('ml_advertiser_id_index', 'ml_scores', ['advertiser_id'], unique=False, postgresql_using='hash')
    op.create_index('ml_client_id_index', 'ml_scores', ['client_id'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('client_id_index', table_name='ml_scores', postgresql_using='hash')
    op.drop_index('advertiser_id_index', table_name='ml_scores', postgresql_using='hash')
    op.drop_constraint(None, 'metrics', type_='unique')
    # ### end Alembic commands ###
