"""Add campaigns and days

Revision ID: c440278e30b3
Revises: 0c58152fd484
Create Date: 2025-02-13 09:00:25.143374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c440278e30b3'
down_revision: Union[str, None] = '0c58152fd484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('impressions_limit', sa.Integer(), nullable=False),
    sa.Column('clicks_limit', sa.Integer(), nullable=False),
    sa.Column('cost_per_impression', sa.Float(), nullable=False),
    sa.Column('cost_per_click', sa.Float(), nullable=False),
    sa.Column('ad_title', sa.String(), nullable=False),
    sa.Column('ad_text', sa.String(), nullable=False),
    sa.Column('start_date', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Integer(), nullable=False),
    sa.Column('target_gender', sa.Enum('MALE', 'FEMALE', 'ALL', name='targetinggender'), nullable=True),
    sa.Column('target_age_from', sa.Integer(), nullable=True),
    sa.Column('target_age_to', sa.Integer(), nullable=True),
    sa.Column('target_location', sa.String(), nullable=True),
    sa.Column('advertiser_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'ml_scores', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ml_scores', type_='unique')
    op.drop_table('campaigns')
    op.drop_table('settings')
    # ### end Alembic commands ###
